title = "my gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Ignore Podfile.lock files as they contain package checksums that trigger false positives"
paths = [
    '''ios/Podfile\.lock''',
    '''android/.*\.lock''',
]

[[rules]]
id = "datadog-access-token"
description = "Detected a Datadog Access Token, potentially risking monitoring and analytics data exposure and manipulation."
regex = '''(?i)(?:datadog)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}([a-z0-9]{40})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
keywords = [
    "datadog",
]
[rules.allowlist]

regexTarget = "line"
regexes = [
  '''DatadogSDKReactNative''',
  '''DatadogWebViewTracking''',
  '''DatadogTrace''',
  '''DatadogLogs''',
  '''DatadogInternal''',
  '''DatadogCrashReporting''',
  '''DatadogCore''',
]