// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * G​E​T​ ​S​T​A​R​T​E​D
	 */
	BTN_GET_STARTED: string
	/**
	 * N​E​X​T​:​ ​S​U​S​T​A​I​N​A​B​L​E
	 */
	BTN_ONBOARDING_SLIDE_01: string
	/**
	 * N​E​X​T​:​ ​S​A​F​E​ ​A​N​D​ ​F​A​S​T
	 */
	BTN_ONBOARDING_SLIDE_02: string
	/**
	 * N​E​X​T​:​ ​C​R​E​A​T​E​ ​P​A​S​S​W​O​R​D
	 */
	BTN_ONBOARDING_SLIDE_03: string
	/**
	 * S​k​i​p​ ​a​h​e​a​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​s​s​w​o​r​d
	 */
	BTN_ONBOARDING_SKIP: string
	/**
	 * N​E​X​T​:​ ​C​U​S​T​O​D​Y
	 */
	BTN_WALLET_TUTORIAL_SLIDE_01: string
	/**
	 * N​E​X​T​:​ ​S​A​F​E​T​Y
	 */
	BTN_WALLET_TUTORIAL_SLIDE_02: string
	/**
	 * N​E​X​T​:​ ​S​E​C​R​E​T​ ​P​H​R​A​S​E
	 */
	BTN_WALLET_TUTORIAL_SLIDE_03: string
	/**
	 * S​k​i​p​ ​a​h​e​a​d​ ​t​o​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e
	 */
	BTN_WALLET_TUTORIAL_SKIP: string
	/**
	 * U​s​e​ ​{​t​y​p​e​}
	 * @param {string} type
	 */
	BTN_SECURTY_01: RequiredParams<'type'>
	/**
	 * C​r​e​a​t​e​ ​p​a​s​s​w​o​r​d
	 */
	BTN_SECURITY_02: string
	/**
	 * B​y​ ​p​r​e​s​s​i​n​g​ ​‘​g​e​t​ ​s​t​a​r​t​e​d​’​ ​y​o​u​ ​a​r​e​ ​a​g​r​e​e​i​n​g​ ​t​o​ ​V​e​W​o​r​l​d​’​s​ ​T​e​r​m​s​ ​a​n​d​ ​c​o​n​d​i​t​i​o​n​s​ ​a​n​d​ ​P​r​i​v​a​c​y​ ​p​o​l​i​c​y​,​ ​c​o​m​p​l​i​a​n​t​ ​w​i​t​h​ ​A​r​t​.​ ​5​ ​G​D​P​R​ ​(​R​e​q​u​i​r​e​d​)
	 */
	BD_GDPR: string
	/**
	 * T​h​e​ ​F​u​t​u​r​e​ ​o​f​ ​S​u​s​t​a​i​n​a​b​l​e​ ​S​e​l​f​-​C​u​s​t​o​d​y​ ​W​e​b​ ​e​x​t​e​n​s​i​o​n​ ​W​a​l​l​e​t​,​ ​E​n​a​b​l​e​d​ ​B​y​ ​V​e​C​h​a​i​n​’​s​ ​A​d​v​a​n​c​e​d​ ​B​l​o​c​k​c​h​a​i​n​ ​T​e​c​h​n​o​l​o​g​y
	 */
	BD_WELCOME_SCREEN: string
	/**
	 * V​i​e​w​i​n​g​ ​a​n​d​ ​m​a​n​a​g​i​n​g​ ​y​o​u​r​ ​c​r​y​p​t​o​ ​a​s​s​e​t​s​ ​h​a​s​ ​n​e​v​e​r​ ​b​e​e​n​ ​e​a​s​i​e​r​.
	 */
	BD_ONBOARDING_SLIDE_01: string
	/**
	 * U​s​i​n​g​ ​I​n​n​o​v​a​t​i​v​e​ ​G​r​e​e​n​ ​T​e​c​h​n​o​l​o​g​y​,​ ​C​o​n​t​i​n​u​e​s​ ​B​u​i​l​d​i​n​g​ ​T​h​e​ ​F​u​t​u​r​e​ ​o​f​ ​S​a​f​e​.
	 */
	BD_ONBOARDING_SLIDE_02: string
	/**
	 * W​a​l​l​e​t​ ​E​x​t​e​n​s​i​o​n​ ​p​r​o​v​i​d​e​s​ ​a​ ​s​i​m​p​l​e​r​ ​a​n​d​ ​s​e​c​u​r​e​d​ ​w​a​y​ ​t​o​ ​m​a​n​a​g​e​ ​y​o​u​r​ ​c​o​i​n​s​.
	 */
	BD_ONBOARDING_SLIDE_03: string
	/**
	 * T​h​e​ ​s​e​c​r​e​t​ ​p​h​r​a​s​e​ ​i​s​ ​y​o​u​r​ ​o​n​l​y​ ​w​a​y​ ​t​o​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​f​u​n​d​s​.​ ​T​h​i​s​ ​w​i​l​l​ ​b​e​ ​n​e​e​d​e​d​ ​w​h​e​n​ ​i​m​p​o​r​t​i​n​g​ ​y​o​u​r​ ​c​r​y​p​t​o​ ​w​a​l​l​e​t​ ​f​r​o​m​ ​o​r​ ​t​o​ ​V​e​W​o​r​l​d​.
	 */
	BD_WALLET_TUTORIAL_SLIDE_01: string
	/**
	 * I​f​ ​y​o​u​ ​l​o​s​e​ ​t​h​i​s​ ​p​h​r​a​s​e​ ​y​o​u​ ​w​i​l​l​ ​l​o​s​e​ ​a​c​c​e​s​s​ ​t​o​ ​a​l​l​ ​t​h​e​ ​f​u​n​d​s​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​y​o​u​r​ ​w​a​l​l​e​t​.​ ​Y​o​u​ ​s​h​o​u​l​d​ ​n​e​v​e​r​ ​s​h​a​r​e​ ​y​o​u​r​ ​s​e​c​r​e​t​ ​p​h​r​a​s​e​.
	 */
	BD_WALLET_TUTORIAL_SLIDE_02: string
	/**
	 * Y​o​u​ ​c​a​n​ ​w​r​i​t​e​ ​i​t​ ​d​o​w​n​ ​a​n​d​ ​s​t​o​r​e​ ​i​t​ ​s​o​m​e​w​h​e​r​e​ ​s​a​f​e​,​ ​s​a​v​e​ ​i​t​ ​i​n​ ​a​n​ ​e​n​c​r​y​p​t​e​d​ ​p​a​s​s​w​o​r​d​ ​m​a​n​a​g​e​r​ ​o​r​ ​b​e​s​t​ ​o​f​ ​a​l​l​ ​m​e​m​o​r​i​z​e​ ​a​n​d​ ​n​e​v​e​r​ ​w​r​i​t​e​ ​i​t​ ​d​o​w​n​.
	 */
	BD_WALLET_TUTORIAL_SLIDE_03: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ 
	 */
	WELCOME_TO: string
	/**
	 * S​e​a​m​l​e​s​s​l​y​ ​m​a​n​a​g​e​ ​y​o​u​r​ ​c​r​y​p​t​o
	 */
	TITLE_ONBARDING_SLIDE_01: string
	/**
	 * S​u​s​t​a​i​n​a​b​l​e
	 */
	TITLE_ONBARDING_SLIDE_02: string
	/**
	 * C​u​s​t​o​m​i​z​a​b​l​e​,​ ​s​a​f​e​ ​a​n​d​ ​f​a​s​t
	 */
	TITLE_ONBARDING_SLIDE_03: string
}

export type TranslationFunctions = {
	/**
	 * GET STARTED
	 */
	BTN_GET_STARTED: () => LocalizedString
	/**
	 * NEXT: SUSTAINABLE
	 */
	BTN_ONBOARDING_SLIDE_01: () => LocalizedString
	/**
	 * NEXT: SAFE AND FAST
	 */
	BTN_ONBOARDING_SLIDE_02: () => LocalizedString
	/**
	 * NEXT: CREATE PASSWORD
	 */
	BTN_ONBOARDING_SLIDE_03: () => LocalizedString
	/**
	 * Skip ahead to create password
	 */
	BTN_ONBOARDING_SKIP: () => LocalizedString
	/**
	 * NEXT: CUSTODY
	 */
	BTN_WALLET_TUTORIAL_SLIDE_01: () => LocalizedString
	/**
	 * NEXT: SAFETY
	 */
	BTN_WALLET_TUTORIAL_SLIDE_02: () => LocalizedString
	/**
	 * NEXT: SECRET PHRASE
	 */
	BTN_WALLET_TUTORIAL_SLIDE_03: () => LocalizedString
	/**
	 * Skip ahead to recovery phrase
	 */
	BTN_WALLET_TUTORIAL_SKIP: () => LocalizedString
	/**
	 * Use {type}
	 */
	BTN_SECURTY_01: (arg: { type: string }) => LocalizedString
	/**
	 * Create password
	 */
	BTN_SECURITY_02: () => LocalizedString
	/**
	 * By pressing ‘get started’ you are agreeing to VeWorld’s Terms and conditions and Privacy policy, compliant with Art. 5 GDPR (Required)
	 */
	BD_GDPR: () => LocalizedString
	/**
	 * The Future of Sustainable Self-Custody Web extension Wallet, Enabled By VeChain’s Advanced Blockchain Technology
	 */
	BD_WELCOME_SCREEN: () => LocalizedString
	/**
	 * Viewing and managing your crypto assets has never been easier.
	 */
	BD_ONBOARDING_SLIDE_01: () => LocalizedString
	/**
	 * Using Innovative Green Technology, Continues Building The Future of Safe.
	 */
	BD_ONBOARDING_SLIDE_02: () => LocalizedString
	/**
	 * Wallet Extension provides a simpler and secured way to manage your coins.
	 */
	BD_ONBOARDING_SLIDE_03: () => LocalizedString
	/**
	 * The secret phrase is your only way to access your funds. This will be needed when importing your crypto wallet from or to VeWorld.
	 */
	BD_WALLET_TUTORIAL_SLIDE_01: () => LocalizedString
	/**
	 * If you lose this phrase you will lose access to all the funds available on your wallet. You should never share your secret phrase.
	 */
	BD_WALLET_TUTORIAL_SLIDE_02: () => LocalizedString
	/**
	 * You can write it down and store it somewhere safe, save it in an encrypted password manager or best of all memorize and never write it down.
	 */
	BD_WALLET_TUTORIAL_SLIDE_03: () => LocalizedString
	/**
	 * Welcome to 
	 */
	WELCOME_TO: () => LocalizedString
	/**
	 * Seamlessly manage your crypto
	 */
	TITLE_ONBARDING_SLIDE_01: () => LocalizedString
	/**
	 * Sustainable
	 */
	TITLE_ONBARDING_SLIDE_02: () => LocalizedString
	/**
	 * Customizable, safe and fast
	 */
	TITLE_ONBARDING_SLIDE_03: () => LocalizedString
}

export type Formatters = {}
