/**
 * Try to keep these names consistent. Trying to stick to the rough convention of: <DOMAIN>_<ACTION>_<RESULT>
 */
export enum AnalyticsEvent {
    /**
     * Security
     */
    APP_PIN_UNLOCKED = "APP_PIN_UNLOCKED",
    APP_WRONG_PIN = "APP_WRONG_PIN",
    APP_BIOMETRICS_UNLOCKED = "APP_BIOMETRICS_UNLOCKED",

    /**
     * DApps
     */
    DAPP_TX_REQUESTED = "DAPP_TX_REQUESTED",
    DAPP_TX_SENT = "DAPP_TX_SENT",
    DAPP_TX_FAILED_TO_SEND = "DAPP_TX_FAILED_TO_SEND",

    DAPP_REQUEST_CERTIFICATE = "DAPP_REQUEST_CERTIFICATE",
    DAPP_CERTIFICATE_SUCCESS = "DAPP_CERTIFICATE_SUCCESS",
    DAPP_CERTIFICATE_FAILED = "DAPP_CERTIFICATE_FAILED",
    DAPP_CERTIFICATE_REJECTED = "DAPP_CERTIFICATE_REJECTED",

    /**
     * Tokens
     */
    TOKENS_CUSTOM_TOKEN_ADDED = "TOKENS_CUSTOM_TOKEN_ADDED",

    /**
     * Fungible Token TXs
     */
    SEND_FUNGIBLE_SENT = "SEND_FUNGIBLE_SENT",
    SEND_FUNGIBLE_FAILED_TO_SEND = "SEND_FUNGIBLE_FAILED_TO_SEND",

    /**
     * Fungible Token TXs
     */
    SEND_NFT_SENT = "SEND_NFT_SENT",
    SEND_NFT_FAILED_TO_SEND = "SEND_NFT_FAILED_TO_SEND",

    /**
     * Add wallets/accounts Events
     */
    WALLET_ADD_LEDGER_SUCCESS = "WALLET_ADD_LEDGER_SUCCESS",
    WALLET_ADD_LEDGER_ERROR = "WALLET_ADD_LEDGER_ERROR",
    WALLET_ADD_LOCAL_SUCCESS = "WALLET_ADD_LOCAL_SUCCESS",
    WALLET_ADD_LOCAL_ERROR = "WALLET_ADD_LOCAL_ERROR",
    PAGE_LOADED_IMPORT_OR_CREATE = "PAGE_LOADED_IMPORT_OR_CREATE",
    PAGE_LOADED_SETUP_PASSWORD = "PAGE_LOADED_SETUP_PASSWORD",
    PASSWORD_SETUP_SUBMITTED = "PASSWORD_SETUP_SUBMITTED",
    NEW_WALLET_VERIFICATION_ATTEMPTED = "NEW_WALLET_VERIFICATION_ATTEMPTED",
    NEW_WALLET_VERIFICATION_SUCCESS = "NEW_WALLET_VERIFICATION_SUCCESS",
    NEW_WALLET_VERIFICATION_FAILED = "NEW_WALLET_VERIFICATION_FAILED",
    NEW_WALLET_PROCEED_TO_VERIFY = "NEW_WALLET_PROCEED_TO_VERIFY",
    IMPORT_MNEMONIC_SUBMITTED = "IMPORT_MNEMONIC_SUBMITTED",
    IMPORT_MNEMONIC_FAILED = "IMPORT_MNEMONIC_FAILED",
    IMPORT_HW_PAGE_LOADED = "IMPORT_HW_PAGE_LOADED",
    IMPORT_HW_FOUND_LEDGER_DETAILS = "IMPORT_HW_FOUND_LEDGER_DETAILS",
    IMPORT_HW_SELECTED_LEDGER = "IMPORT_HW_SELECTED_LEDGER",
    IMPORT_HW_FAILED_TO_IMPORT = "IMPORT_HW_FAILED_TO_IMPORT",
    IMPORT_HW_USER_SUBMITTED_ACCOUNTS = "IMPORT_HW_USER_SUBMITTED_ACCOUNTS",
    COMPLETED_WALLET_SCREEN = "COMPLETED_WALLET_SCREEN",
    SELECT_WALLET_CREATE_WALLET = "SELECT_WALLET_CREATE_WALLET",
    SELECT_WALLET_IMPORT_WALLET = "SELECT_WALLET_IMPORT_WALLET",
    SELECT_WALLET_IMPORT_MNEMONIC = "SELECT_WALLET_IMPORT_MNEMONIC",
    SELECT_WALLET_IMPORT_HARDWARE = "SELECT_WALLET_IMPORT_HARDWARE",
}
