const EXCHANGE_CLIENT_AXIOS_TIMEOUT = Number(
    process.env.REACT_APP_EXCHANGE_CLIENT_AXIOS_TIMEOUT || "5000",
)

export const EXCHANGE_CLIENT_AXIOS_OPTS = {
    timeout: EXCHANGE_CLIENT_AXIOS_TIMEOUT,
}
