import { combineReducers } from "redux"
import {
    AccountSlice,
    ActivitiesSlice,
    B3moSlice,
    B3moSessionSlice,
    BalanceSlice,
    BeatSlice,
    CacheSlice,
    ContactsSlice,
    CurrencySlice,
    DelegationSlice,
    DeviceSlice,
    DiscoverySlice,
    NetworkSlice,
    NftSlice,
    NftSliceState,
    PendingSlice,
    TokenSlice,
    UserPreferencesSlice,
    WalletConnectSessionsSlice,
    AnalyticsSlice,
    BrowserSlice,
    Notification,
    VersionUpdateSlice,
    ExternalDappsSlice,
    WalletPreferencesSlice,
} from "./Slices"
import { persistReducer } from "redux-persist"
import { PersistConfig } from "redux-persist/es/types"

export const reducer = (nftPersistConfig: PersistConfig<NftSliceState>) =>
    combineReducers({
        [CurrencySlice.name]: CurrencySlice.reducer,
        [TokenSlice.name]: TokenSlice.reducer,
        [UserPreferencesSlice.name]: UserPreferencesSlice.reducer,
        [DeviceSlice.name]: DeviceSlice.reducer,
        [AccountSlice.name]: AccountSlice.reducer,
        [NetworkSlice.name]: NetworkSlice.reducer,
        [BalanceSlice.name]: BalanceSlice.reducer,
        [CacheSlice.name]: CacheSlice.reducer,
        [ContactsSlice.name]: ContactsSlice.reducer,
        [ActivitiesSlice.name]: ActivitiesSlice.reducer,
        [DelegationSlice.name]: DelegationSlice.reducer,
        [NftSlice.name]: persistReducer(nftPersistConfig, NftSlice.reducer), // persist specific keys from a reducer
        [WalletConnectSessionsSlice.name]: WalletConnectSessionsSlice.reducer,
        [PendingSlice.name]: PendingSlice.reducer,
        [BeatSlice.name]: BeatSlice.reducer,
        [DiscoverySlice.name]: DiscoverySlice.reducer,
        [AnalyticsSlice.name]: AnalyticsSlice.reducer,
        [BrowserSlice.name]: BrowserSlice.reducer,
        [Notification.name]: Notification.reducer,
        [VersionUpdateSlice.name]: VersionUpdateSlice.reducer,
        [ExternalDappsSlice.name]: ExternalDappsSlice.reducer,
        [WalletPreferencesSlice.name]: WalletPreferencesSlice.reducer,
        [B3moSlice.name]: B3moSlice.reducer,
        [B3moSessionSlice.name]: B3moSessionSlice.reducer,
    })
