export enum ActivityStatus {
    PENDING = "PENDING",
    REVERTED = "REVERTED",
    SUCCESS = "SUCCESS",
}

export enum ActivityType {
    CONNECTED_APP_TRANSACTION = "CONNECTED_APP_TRANSACTION",
    SIGN_CERT = "SIGN_CERT", // local
    SIGN_TYPED_DATA = "SIGN_TYPED_DATA", // local
    DAPP_LOGIN = "DAPP_LOGIN", // local

    DAPP_TRANSACTION = "DAPP_TRANSACTION",

    // New types
    B3TR_SWAP_VOT3_TO_B3TR = "B3TR_SWAP_VOT3_TO_B3TR",
    B3TR_SWAP_B3TR_TO_VOT3 = "B3TR_SWAP_B3TR_TO_VOT3",
    B3TR_PROPOSAL_SUPPORT = "B3TR_PROPOSAL_SUPPORT",
    B3TR_CLAIM_REWARD = "B3TR_CLAIM_REWARD",
    B3TR_UPGRADE_GM = "B3TR_UPGRADE_GM", //
    B3TR_ACTION = "B3TR_ACTION",
    B3TR_PROPOSAL_VOTE = "B3TR_PROPOSAL_VOTE",
    B3TR_XALLOCATION_VOTE = "B3TR_XALLOCATION_VOTE",
    TRANSFER_VET = "TRANSFER_VET",
    TRANSFER_FT = "TRANSFER_FT",
    TRANSFER_NFT = "TRANSFER_NFT",
    NFT_SALE = "NFT_SALE",
    TRANSFER_SF = "TRANSFER_SF",
    SWAP_VET_TO_FT = "SWAP_VET_TO_FT",
    SWAP_FT_TO_VET = "SWAP_FT_TO_VET",
    SWAP_FT_TO_FT = "SWAP_FT_TO_FT",
    UNKNOWN_TX = "UNKNOWN_TX",
    STARGATE_CLAIM_REWARDS_BASE_LEGACY = "STARGATE_CLAIM_REWARDS_BASE_LEGACY",
    STARGATE_CLAIM_REWARDS_DELEGATE_LEGACY = "STARGATE_CLAIM_REWARDS_DELEGATE_LEGACY",
    STARGATE_DELEGATE_LEGACY = "STARGATE_DELEGATE_LEGACY",
    STARGATE_STAKE = "STARGATE_STAKE",
    STARGATE_UNDELEGATE_LEGACY = "STARGATE_UNDELEGATE_LEGACY",
    STARGATE_UNSTAKE = "STARGATE_UNSTAKE",
    STARGATE_CLAIM_REWARDS = "STARGATE_CLAIM_REWARDS",
    STARGATE_BOOST = "STARGATE_BOOST",
    STARGATE_DELEGATE_REQUEST = "STARGATE_DELEGATE_REQUEST",
    STARGATE_DELEGATE_EXIT_REQUEST = "STARGATE_DELEGATE_EXIT_REQUEST",
    STARGATE_DELEGATION_EXITED = "STARGATE_DELEGATION_EXITED",
    STARGATE_DELEGATION_EXITED_VALIDATOR = "STARGATE_DELEGATION_EXITED_VALIDATOR",
    STARGATE_DELEGATE_ACTIVE = "STARGATE_DELEGATE_ACTIVE",
    STARGATE_MANAGER_ADDED = "STARGATE_MANAGER_ADDED",
    STARGATE_MANAGER_REMOVED = "STARGATE_MANAGER_REMOVED",
    VEVOTE_VOTE_CAST = "VEVOTE_VOTE_CAST",
}

export enum ActivityEvent {
    B3TR_SWAP_VOT3_TO_B3TR = "B3TR_SWAP_VOT3_TO_B3TR",
    B3TR_SWAP_B3TR_TO_VOT3 = "B3TR_SWAP_B3TR_TO_VOT3",
    B3TR_PROPOSAL_SUPPORT = "B3TR_PROPOSAL_SUPPORT",
    B3TR_CLAIM_REWARD = "B3TR_CLAIM_REWARD",
    B3TR_UPGRADE_GM = "B3TR_UPGRADE_GM", //
    B3TR_ACTION = "B3TR_ACTION",
    B3TR_PROPOSAL_VOTE = "B3TR_PROPOSAL_VOTE",
    B3TR_XALLOCATION_VOTE = "B3TR_XALLOCATION_VOTE",
    TRANSFER_VET = "TRANSFER_VET",
    TRANSFER_FT = "TRANSFER_FT",
    TRANSFER_NFT = "TRANSFER_NFT",
    NFT_SALE = "NFT_SALE",
    TRANSFER_SF = "TRANSFER_SF",
    SWAP_VET_TO_FT = "SWAP_VET_TO_FT",
    SWAP_FT_TO_VET = "SWAP_FT_TO_VET",
    SWAP_FT_TO_FT = "SWAP_FT_TO_FT",
    UNKNOWN_TX = "UNKNOWN_TX",
    STARGATE_BOOST = "STARGATE_BOOST",
    STARGATE_CLAIM_REWARDS = "STARGATE_CLAIM_REWARDS",
    STARGATE_CLAIM_REWARDS_BASE_LEGACY = "STARGATE_CLAIM_REWARDS_BASE_LEGACY",
    STARGATE_CLAIM_REWARDS_DELEGATE_LEGACY = "STARGATE_CLAIM_REWARDS_DELEGATE_LEGACY",
    STARGATE_DELEGATE_LEGACY = "STARGATE_DELEGATE_LEGACY",
    STARGATE_DELEGATE_ACTIVE = "STARGATE_DELEGATE_ACTIVE",
    STARGATE_DELEGATE_EXIT_REQUEST = "STARGATE_DELEGATE_EXIT_REQUEST",
    STARGATE_DELEGATION_EXITED = "STARGATE_DELEGATION_EXITED",
    STARGATE_DELEGATION_EXITED_VALIDATOR = "STARGATE_DELEGATION_EXITED_VALIDATOR",
    STARGATE_DELEGATE_REQUEST = "STARGATE_DELEGATE_REQUEST",
    STARGATE_MANAGER_ADDED = "STARGATE_MANAGER_ADDED",
    STARGATE_MANAGER_REMOVED = "STARGATE_MANAGER_REMOVED",
    STARGATE_STAKE = "STARGATE_STAKE",
    STARGATE_UNDELEGATE_LEGACY = "STARGATE_UNDELEGATE_LEGACY",
    STARGATE_UNSTAKE = "STARGATE_UNSTAKE",
    VEVOTE_VOTE_CAST = "VEVOTE_VOTE_CAST",
}

export enum ActivitySearchBy {
    TO = "to",
    FROM = "from",
    ORIGIN = "origin",
    GAS_PAYER = "gasPayer",
}

export enum ActivitySupport {
    AGAINST = "AGAINST",
    FOR = "FOR",
    ABSTAIN = "ABSTAIN",
}
