export enum Routes {
    WELCOME = "Welcome",
    ONBOARDING = "Onboarding",
    WALLET_TUTORIAL = "Wallet_Tutorial",
    WALLET_TPYE_CREATION = "Wallet_Type_Creation",
    WALLET_TPYE_IMPORT = "Wallet_Type_Import",
    SEED_PHRASE = "Seed_Phrase",
    CONFIRM_SEED_PHRASE = "Confirm_Seed_Phrase",
    IMPORT_SEED_PHRASE = "Import_Seed_Phrase",
    USER_CREATE_PASSWORD = "User_Create_Password",
    APP_SECURITY = "App_Security",
    SETTINGS = "Settings",
    CREATE_WALLET_FLOW = "Create_Wallet_Flow",
    WALLET_SUCCESS = "Wallet_Success",
}
