export enum Routes {
    WELCOME = "Welcome",
    ONBOARDING = "Onboarding",
    WALLET_TUTORIAL = "Wallet_Tutorial",
    WALLET_TYPE_CREATION = "Wallet_Type_Creation",
    WALLET_TYPE_IMPORT = "Wallet_Type_Import",
    SEED_PHRASE = "Seed_Phrase",
    CONFIRM_SEED_PHRASE = "Confirm_Seed_Phrase",
    IMPORT_SEED_PHRASE = "Import_Seed_Phrase",
    USER_CREATE_PASSWORD = "User_Create_Password",
    APP_SECURITY = "App_Security",
    SETTINGS = "Settings",
    CREATE_WALLET_FLOW = "Create_Wallet_Flow",
    WALLET_SUCCESS = "Wallet_Success",
    HOME = "Home",
    WALLET_MANAGEMENT = "Wallet_Management",
    SETTINGS_GENERAL = "Settings_General",
    SETTINGS_ADVANCED = "Settings_Advanced",
    SETTINGS_NFT = "Settings_NFT",
    SETTINGS_NETWORK = "Settings_Network",
    SETTINGS_CONTACTS = "Settings_Contacts",
    SETTINGS_PRIVACY = "Settings_Privacy",
    SETTINGS_ALERTS = "Settings_Alerts",
    SETTINGS_CONNECTED_APPS = "Settings_Connected_Apps",
    SETTINGS_ABOUT = "Settings_About",
    SETTINGS_CUSTOM_NET = "Settings_Custom_Network",
}
