/* eslint-disable max-len*/

export type DiscoveryDApp = {
    name: string
    href: string
    desc?: string
    category?: string
    tags?: string[]
    contracts?: string[]
    repo?: string
    createAt: number
    image?: object
    isCustom: boolean
    amountOfNavigations: number
}

// hostname should be the URL hostname of the dapp

const DAppConfig: DiscoveryDApp[] = [
    {
        name: "vechain Rewards dApp",
        href: "https://app.rewards.vechain.org/dashboard",
        desc: "Explore the Official vechain Rewards dApp - Your solution to effortlessly manage x-nodes, claim rewards and track your reward history. Get started now!",
        category: "defi",
        tags: ["nft", "vip181", "rewards", "staking", "x-nodes", "defi"],
        contracts: ["0xb81e9c5f9644dec9e5e3cac86b4461a222072302"],
        createAt: 1694444477000,
        image: require("./images/org.vechain.rewards.app.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "WorldOfV NFT Marketplace",
        href: "https://worldofv.art/",
        desc: "The first gas-free, green NFT platform built on the VeChain blockchain",
        category: "marketplaces",
        tags: ["WOV", "World Of V NFTs'", "NFTs", "Digital Art", "Phygital", "Artists"],
        createAt: 1637639264000,
        image: require("./images/com.worldofv.marketplace-nft.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "VeSea Marketplace",
        href: "https://vesea.io",
        desc: "A peer-to-peer marketplace for NFTs, rare digital items and crypto collectibles on the VeChain blockchain.",
        category: "marketplaces",
        tags: ["nft", "vekings", "vesea", "market", "buy", "sell", "bid", "trade", "marketplace"],
        createAt: 1633530911000,
        image: require("./images/io.vesea.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "vechain.energy · blockchain development platform",
        href: "https://vechain.energy/",
        desc: "Simplify and streamline your blockchain development with our platform. No more web3 or gas fees, access blockchains as easily as a regular backend. Complex transactions made easy through our sponsorship services, improve your application today.",
        category: "utilities",
        tags: ["developer", "vtho", "api"],
        createAt: 1611544407000,
        image: require("./images/energy.vechain.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "Fiat On-Ramp",
        href: "https://ramp.vechain.energy/",
        desc: "Buy VET using Fiat from many different currencies. Also available as dApp implementation.",
        category: "defi",
        tags: ["vet", "fiat", "ramp", "developer"],
        createAt: 1691736378000,
        image: require("./images/energy.vechain.ramp.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "Token Swap / Exchange",
        href: "https://swap.vechain.energy/",
        desc: "Swap Tokens from other Networks to Vechain. Also available as dApp implementation.",
        category: "defi",
        tags: ["vet", "swap", "exchange", "developer", "vtho"],
        createAt: 1690983864000,
        image: require("./images/energy.vechain.swap.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "OceanEx NFT Marketplace",
        href: "https://nft.oceanex.pro/",
        desc: "The markeplace for trading NFTs and crypto collections built on the VeChain blockchain and powered by OceanEx.",
        category: "marketplaces",
        tags: ["NFT", "OceanEx", "vip181"],
        createAt: 1670903394000,
        image: require("./images/pro.oceanex.nft.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "VeVote",
        href: "https://vevote.vechain.org/",
        desc: "A decentralized voting platform for the VeChain ecosystem.",
        category: "utilities",
        tags: ["voting"],
        repo: "https://github.com/vechain/vevote-contracts",
        contracts: ["0xa6416a72f816d3a69f33d0814700545c8e3fe4be", "0x7e54f0790153647ec0651c35ced28171adb5d44a"],
        createAt: 1575613895000,
        image: require("./images/com.vechain.vevote.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "VTHO Exchange",
        href: "https://vtho.exchange/",
        desc: "Automatically Swap generated VTHO into other Tokens.",
        category: "defi",
        tags: ["vet", "vtho", "swap", "exchange", "vtho"],
        createAt: 1695719391000,
        image: require("./images/exchange.vtho.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "Token Transfer",
        href: "https://vet-token-transfer.vercel.app/",
        desc: "Transfer any of the VIP-180 tokens in the vechain ecosystem!",
        category: "utilities",
        tags: ["transfer", "tokens", "tool", "utility"],
        createAt: 1684139476000,
        image: require("./images/app.vercel.vet-token-transfer.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "Non FungiBulls",
        href: "https://non-fungibulls.com",
        desc: "Non FungiBulls is a collection of 1,450 NFTs on the VechainThor blockchain. It is a community based utility collection and a support token for our main project, Non Fungible News.",
        category: "collectibles",
        tags: ["NFT", "non fungibulls", "Collectibles", "VNFT", "Non Fungible News"],
        createAt: 1675842196000,
        image: require("./images/com.non-fungibulls.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "Defi Bet Club",
        href: "https://app.defibetclub.com/",
        desc: "A fun, safe private members club built on VeChain for sports betting enthusiasts!",
        category: "games",
        tags: ["NFT", "Bets", "Sports", "VIP-181", "Collectibles", "Gambling"],
        createAt: 1675318630000,
        image: require("./images/com.defibetclub.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "3DAbles",
        href: "https://3dables.smuzzies.com/",
        desc: "3DAbles is a collection of user generated artwork spanning the entire VeChainThor ecosystem and is a product of the Smuzzies development team.",
        category: "collectibles",
        tags: ["Smuzzies", "VIP-181", "Collectibles", "VNFT", "NFT"],
        createAt: 1668394330000,
        image: require("./images/com.smuzzies.3dables.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "VeFam",
        href: "https://vefam.com/#/home",
        desc: "VeFam distributes and incubates NFT games, GameFi projects, including unique NFT collections and highly entertaining games.",
        category: "games",
        tags: [
            "game",
            "games",
            "NFT",
            "NFT game",
            "gameFi",
            "VeFam",
            "Collectibles",
            "VNFT",
            "DeFi",
            "VIP-180",
            "VIP-181",
            "VIP-210",
        ],
        createAt: 1666668513000,
        image: require("./images/com.vefam.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "VeRocket (ZumoSwap)",
        href: "https://app.verocket.com",
        desc: "Fast token swap service built for VeChain (formerly ZumoSwap)",
        category: "defi",
        tags: ["tool", "tokens", "VIP-180"],
        createAt: 1644245405000,
        image: require("./images/com.verocket.app.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
    {
        name: "BlackVeMarket",
        href: "https://blackvemarket.com",
        desc: "Discover Limitless NFT Experiences with BlackVeMarket: Where the VeFam Unites! Join our Vibrant Community and Explore the Boundless World of Digital Collectibles, Trading, and Creativity. Embrace the Future of NFTs and Unleash Your Imagination with BlackVeMarket!",
        category: "marketplaces",
        tags: ["NFT", "Marketplace", "VIP-181", "Collectibles", "VNFT", "BlackVe"],
        createAt: 1641010398000,
        image: require("./images/com.blackvemarket.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },

    {
        name: "Inspector",
        href: "https://inspector.vecha.in/#/contracts",
        desc: "A tool that allows you to deploy and interact with the contract",
        category: "utilities",
        tags: ["contract", "deploy", "tool"],
        repo: "https://github.com/vechain/inspector-app",
        createAt: 1552446522000,
        image: require("./images/com.vechain.inspector.png"),
        isCustom: false,
        amountOfNavigations: 0,
    },
]

export { DAppConfig }
