export type TFonts =
    | 'largeTitle'
    | 'title'
    | 'subTitle'
    | 'body'
    | 'footnote'
    | 'caption'
    | 'largeTitle_accent'
    | 'title_accent'
    | 'subTitle_accent'
    | 'body_accent'
    | 'footnote_accent'
    | 'caption_accent'
