name: E2E Testing Overnight

on:
    workflow_dispatch:
    schedule:
        # Runs at 22:00 UTC every Monday to Friday
        - cron: '0 22 * * 1-5'
        
jobs:
    e2e-ios:
        uses: ./.github/workflows/e2e.yml
        with:
            platform: ios
            parallel: 2
        secrets: inherit
    e2e-android:
        uses: ./.github/workflows/e2e.yml
        with:
            platform: android
            parallel: 1
        secrets: inherit

    
