name: Merge dev-test into develop with E2E Test

on:
  schedule:
    - cron: '0 19 * * 1-5'  # This schedule runs every day at 7pm UTC. Adjust the cron expression based on your timezone.
  push:
   branches:
    - dev-test
  workflow_dispatch:
    inputs:
        manual-trigger:
            description: 'Manually trigger the workflow'
            default: 'false'
permissions: 
    contents: write # This is required for actions/checkout
    pull-requests: write # This is required for pull request comments
jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Check for changes
      run: |
        git fetch origin develop
        git checkout develop
        git fetch origin dev-test
        git checkout dev-test
        changes=$(git rev-list --count develop..dev-test)
        echo "Number of changes between develop and dev-test: $changes"
        if [ "$changes" -eq 0 ]; then
            echo "No changes to merge. Exiting workflow."
            exit 0
        fi
      

  e2e-ios:
    uses: ./.github/workflows/e2e.yml
    with:
        platform: ios
        parallel: 2
    secrets: inherit
  e2e-android:
    uses: ./.github/workflows/e2e.yml
    with:
        platform: android
        parallel: 1
    secrets: inherit
  

  
  merge:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
       - uses: actions/checkout@v2
       - uses: everlytic/branch-merge@1.1.5
         with:
            github_token: ${{ secrets.VEWORLD_PAT }}
            source_ref: ${{ github.ref }}
            target_branch: 'develop'
            commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'