name: Merge Develop into Main with E2E Test

on:
  schedule:
    - cron: '0 19 * * 1-5'  # This schedule runs every day at 7pm UTC. Adjust the cron expression based on your timezone.
  workflow_dispatch:
    inputs:
        manual-trigger:
            description: 'Manually trigger the workflow'
            default: 'false'

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for changes
      run: |
        git fetch
        changes=$(git rev-list --count main..develop)
        if [ "$changes" -eq 0 ]; then
            echo "No changes to merge. Exiting workflow."
            exit 0
        fi
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Run E2E Test
      uses: ./.github/workflows/e2e.yml 

  merge-develop-into-main:
    runs-on: ubuntu-latest
    needs: e2e-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout main and merge develop in
      run: |
        git checkout main
        git pull origin main
        git merge develop -m "Merge develop into main - $(date +"%Y-%m-%d %H:%M:%S")"
        git push origin main
